import React, { useState, useEffect, useRef, useMemo } from 'react';
import { 
  Play, Pause, RotateCcw, Sun, Moon, Maximize2, 
  ChevronLeft, ChevronRight, Bookmark, GraduationCap, 
  Clock, User, Calendar, Award, BookOpen, AlertCircle, 
  TrendingUp, BarChart2, CheckCircle2, XCircle, Sparkles
} from 'lucide-react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

// Import Compiled Presentation Data (will be generated by convert.py)
import presentationData from './presentation-data.json';

// === DYNAMIC REACT WIDGETS REGISTRY ===

// 1. ROI Widget
function ROIWidget() {
  const [facultyCount, setFacultyCount] = useState(100);
  const [hoursSavedPerWeek, setHoursSavedPerWeek] = useState(4);
  const hourlyRate = 50; // $50/hour average cost of faculty time
  
  const weeklySavings = facultyCount * hoursSavedPerWeek * hourlyRate;
  const annualSavings = weeklySavings * 40; // 40 weeks per academic year
  
  return (
    <div className="p-5 border border-slate-800 rounded-xl bg-slate-900/60 my-4 text-left">
      <h4 className="text-sm font-bold uppercase tracking-wider text-sky-400 mb-3 flex items-center gap-1.5">
        <TrendingUp className="h-4 w-4" /> ROI Calculator: Time & Cost Savings
      </h4>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label className="text-xs text-slate-400 block mb-1">Faculty Count: {facultyCount}</label>
          <input 
            type="range" 
            min="10" 
            max="500" 
            value={facultyCount} 
            onChange={(e) => setFacultyCount(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400"
          />
        </div>
        <div>
          <label className="text-xs text-slate-400 block mb-1">Weekly Hours Saved: {hoursSavedPerWeek} hrs</label>
          <input 
            type="range" 
            min="1" 
            max="10" 
            value={hoursSavedPerWeek} 
            onChange={(e) => setHoursSavedPerWeek(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400"
          />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3 pt-3 border-t border-slate-800/60 text-center">
        <div className="bg-slate-950/40 p-2.5 rounded-lg border border-slate-800/40">
          <div className="text-[10px] uppercase text-slate-500 font-mono">Weekly Savings</div>
          <div className="text-lg font-bold text-slate-100">${weeklySavings.toLocaleString()}</div>
        </div>
        <div className="bg-slate-950/40 p-2.5 rounded-lg border border-slate-800/40">
          <div className="text-[10px] uppercase text-slate-500 font-mono">Annual Savings</div>
          <div className="text-lg font-bold text-sky-400">${annualSavings.toLocaleString()}</div>
        </div>
      </div>
    </div>
  );
}

// 2. Enrollment Calculator
function EnrollmentCalculator() {
  const [initialStudents, setInitialStudents] = useState(1000);
  const [growthRate, setGrowthRate] = useState(5);
  
  const years = [1, 2, 3, 4, 5];
  const data = years.map(y => {
    const value = Math.round(initialStudents * Math.pow(1 + growthRate/100, y));
    return { year: `Year ${y}`, students: value };
  });

  return (
    <div className="p-5 border border-slate-800 rounded-xl bg-slate-900/60 my-4 text-left">
      <h4 className="text-sm font-bold uppercase tracking-wider text-sky-400 mb-3 flex items-center gap-1.5">
        <BarChart2 className="h-4 w-4" /> Enrollment Growth Predictor
      </h4>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label className="text-xs text-slate-400 block mb-1">Starting Enrollment: {initialStudents}</label>
          <input 
            type="range" 
            min="100" 
            max="10000" 
            value={initialStudents} 
            onChange={(e) => setInitialStudents(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400"
          />
        </div>
        <div>
          <label className="text-xs text-slate-400 block mb-1">Annual Growth Rate: {growthRate}%</label>
          <input 
            type="range" 
            min="-10" 
            max="30" 
            value={growthRate} 
            onChange={(e) => setGrowthRate(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400"
          />
        </div>
      </div>
      <div className="h-40 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
            <XAxis dataKey="year" stroke="#9ca3af" fontSize={10} />
            <YAxis stroke="#9ca3af" fontSize={10} />
            <Tooltip contentStyle={{ backgroundColor: '#0b1726', borderColor: '#1f2937' }} labelStyle={{ color: '#9ca3af' }} />
            <Line type="monotone" dataKey="students" stroke="#E5A823" strokeWidth={2} dot={{ r: 4 }} />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

// 3. Ask AI Widget
function AskAI() {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');
  const [loading, setLoading] = useState(false);
  
  const handleAsk = () => {
    if (!query.trim()) return;
    setLoading(true);
    setResponse('');
    setTimeout(() => {
      setLoading(false);
      if (query.toLowerCase().includes('obi') || query.toLowerCase().includes('outcome')) {
        setResponse("Outcome-Based Education (OBE) defines specific, measurable competencies that students must demonstrate upon completion. AI-Era Education aligns OBE by providing personalized tools to track and accelerate attainment.");
      } else if (query.toLowerCase().includes('portfolio')) {
        setResponse("Portfolio-First learning shift guarantees student showcases demonstrable capabilities (e.g. code repositories, written documents, or physical AI products) instead of simple exam-taking grades.");
      } else {
        setResponse("AI in higher education enables personalized learning paths, automates routine assessments, and allows faculty to pivot from grading administrators into collaborative project coaches.");
      }
    }, 1000);
  };
  
  return (
    <div className="p-5 border border-slate-800 rounded-xl bg-slate-900/60 my-4 text-left">
      <h4 className="text-sm font-bold uppercase tracking-wider text-sky-400 mb-3 flex items-center gap-1.5">
        <GraduationCap className="h-4 w-4" /> Ask AI Tutor Assistant
      </h4>
      <div className="flex gap-2">
        <input 
          type="text" 
          placeholder="Ask a question (e.g., 'What is OBE?' or 'Portfolio pillars?')..." 
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleAsk()}
          className="flex-1 bg-slate-950/80 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-sky-400"
        />
        <button 
          onClick={handleAsk}
          className="px-4 py-1.5 rounded-lg bg-sky-400 hover:bg-sky-500 text-slate-950 font-semibold text-xs transition-colors shrink-0"
        >
          {loading ? 'Thinking...' : 'Submit'}
        </button>
      </div>
      {response && (
        <div className="mt-3 p-3 bg-slate-950/40 border border-slate-800/40 rounded-lg text-xs text-slate-300 leading-relaxed">
          <strong>AI Tutor:</strong> {response}
        </div>
      )}
    </div>
  );
}

// 4. Dynamic Chart Component
function ChartComponent({ type, dataset, x, y }) {
  const datasets = {
    'student-data': [
      { year: '2021', count: 12000 },
      { year: '2022', count: 18000 },
      { year: '2023', count: 25000 },
      { year: '2024', count: 35000 },
      { year: '2025', count: 45000 }
    ],
    'enrollment-data': [
      { year: '2020', students: 10000 },
      { year: '2021', students: 15000 },
      { year: '2022', students: 22000 },
      { year: '2023', students: 31000 },
      { year: '2024', students: 45000 }
    ],
    'ai-adoption': [
      { year: '2023', adoption: 15 },
      { year: '2024', adoption: 40 },
      { year: '2025', adoption: 90 }
    ]
  };

  const data = datasets[dataset] || [];

  return (
    <div className="w-full h-[240px] mt-4 p-4 bg-slate-950/60 border border-slate-800/80 rounded-xl relative text-left">
      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-4">
        Dynamic {type} Chart &bull; Dataset: {dataset}
      </div>
      <ResponsiveContainer width="100%" height="80%">
        {type === 'bar' ? (
          <BarChart data={data}>
            <XAxis dataKey={x} stroke="#64748b" fontSize={11} tickLine={false} />
            <YAxis stroke="#64748b" fontSize={11} tickLine={false} />
            <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #1e293b' }} />
            <Bar dataKey={y} fill="#E5A823" radius={[4, 4, 0, 0]} />
          </BarChart>
        ) : (
          <LineChart data={data}>
            <XAxis dataKey={x} stroke="#64748b" fontSize={11} tickLine={false} />
            <YAxis stroke="#64748b" fontSize={11} tickLine={false} />
            <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #1e293b' }} />
            <Line type="monotone" dataKey={y} stroke="#38bdf8" strokeWidth={3} dot={{ r: 4, fill: '#38bdf8' }} activeDot={{ r: 6 }} />
          </LineChart>
        )}
      </ResponsiveContainer>
    </div>
  );
}

// 5. Simulation Engine
function SimulationEngine() {
  const [training, setTraining] = useState(50);
  const [projects, setProjects] = useState(5);
  const [tutorAdoption, setTutorAdoption] = useState(30);

  const calculateAchievement = () => {
    return Math.min(100, Math.round((training * 0.3) + (projects * 5) + (tutorAdoption * 0.45)));
  };

  const score = calculateAchievement();
  const scoreColor = score >= 80 ? "text-emerald-455 text-emerald-400" : score >= 50 ? "text-sky-400" : "text-rose-400";

  return (
    <div className="p-5 rounded-2xl border border-slate-800 bg-slate-950/60 my-6 text-left animate-fade-up">
      <div className="text-xs font-bold text-sky-400 uppercase tracking-wider mb-4 flex items-center gap-2">
        <TrendingUp className="h-4 w-4" /> OBE Skill Achievement Simulator
      </div>
      
      <div className="space-y-4">
        <div>
          <div className="flex justify-between text-xs text-slate-400 mb-1">
            <span>Faculty Training Completion</span>
            <span className="font-mono text-sky-400">{training}%</span>
          </div>
          <input 
            type="range" min="0" max="100" value={training} 
            onChange={(e) => setTraining(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400" 
          />
        </div>
        
        <div>
          <div className="flex justify-between text-xs text-slate-400 mb-1">
            <span>Industry Portfolio Projects (per student)</span>
            <span className="font-mono text-sky-400">{projects} projects</span>
          </div>
          <input 
            type="range" min="0" max="10" value={projects} 
            onChange={(e) => setProjects(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400" 
          />
        </div>
        
        <div>
          <div className="flex justify-between text-xs text-slate-400 mb-1">
            <span>AI Tutor Adoption Rate</span>
            <span className="font-mono text-sky-400">{tutorAdoption}%</span>
          </div>
          <input 
            type="range" min="0" max="100" value={tutorAdoption} 
            onChange={(e) => setTutorAdoption(Number(e.target.value))}
            className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400" 
          />
        </div>
      </div>

      <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center justify-between">
        <div>
          <div className="text-xs text-slate-500 font-medium">Estimated Outcome Competency</div>
          <div className={`text-3xl font-extrabold ${scoreColor}`}>{score}%</div>
        </div>
        <div className="text-[10px] text-slate-450 max-w-[200px] text-right">
          Target outcome is &gt;85% for full NBA/NAAC validation grade.
        </div>
      </div>
    </div>
  );
}

// 6. Interactive Timeline
function InteractiveTimeline() {
  const [activeStep, setActiveStep] = useState(0);

  const steps = [
    {
      title: "Orientation Phase",
      desc: "Rollout of standard MDX presentation creation instructions to academic leads.",
      highlight: "Month 1"
    },
    {
      title: "Interactive Authoring",
      desc: "Faculty converts classic slides to hybrid interactive modules incorporating quizzes.",
      highlight: "Month 3"
    },
    {
      title: "Vite Deployment",
      desc: "Auto-compilation using convert.py creates responsive learning pages.",
      highlight: "Month 6"
    }
  ];

  return (
    <div className="p-5 rounded-2xl border border-slate-800 bg-slate-950/60 my-6 text-left animate-fade-up">
      <div className="text-xs font-bold text-sky-400 uppercase tracking-wider mb-4">
        Interactive Curriculum Roadmap
      </div>
      
      <div className="flex justify-between items-center relative mb-6">
        <div className="absolute top-1/2 left-0 right-0 h-0.5 bg-slate-800 -translate-y-1/2 z-0" />
        {steps.map((step, idx) => (
          <button
            key={idx}
            onClick={() => setActiveStep(idx)}
            className={`h-8 w-8 rounded-full border-2 flex items-center justify-center text-xs font-bold z-10 transition-all ${
              activeStep === idx 
                ? "bg-sky-400 border-sky-400 text-slate-950 shadow-lg shadow-sky-400/20" 
                : "bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-500"
            }`}
          >
            {idx + 1}
          </button>
        ))}
      </div>

      <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 transition-all duration-300">
        <div className="flex justify-between items-center mb-1">
          <span className="text-xs font-mono font-bold text-sky-400">{steps[activeStep].highlight}</span>
          <span className="text-xs font-bold text-slate-200">{steps[activeStep].title}</span>
        </div>
        <p className="text-xs text-slate-400 leading-relaxed mt-2">{steps[activeStep].desc}</p>
      </div>
    </div>
  );
}

// 7. AI Tutor Interactive Lesson Widget
function AITutor() {
  const [messages, setMessages] = useState([
    { sender: 'tutor', text: "Hi! Let's reflect on Outcome-Based Education. What is the main outcome of your course?" }
  ]);
  const [input, setInput] = useState('');

  const handleSend = () => {
    if (!input.trim()) return;
    const userMsg = input.trim();
    setMessages(prev => [...prev, { sender: 'user', text: userMsg }]);
    setInput('');

    setTimeout(() => {
      setMessages(prev => [
        ...prev,
        { sender: 'tutor', text: "Great point. In standard pedagogy, we evaluate that outcome through project artifacts. Have you structured your portfolio checks yet?" }
      ]);
    }, 1000);
  };

  return (
    <div className="p-5 rounded-2xl border border-slate-800 bg-slate-950/60 my-6 text-left animate-fade-up flex flex-col h-[280px]">
      <div className="text-xs font-bold text-sky-400 uppercase tracking-wider mb-2 flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-sky-400" /> REVA AI Reflection Tutor
      </div>
      
      <div className="flex-1 overflow-y-auto space-y-3 pr-2 mb-3">
        {messages.map((msg, idx) => (
          <div key={idx} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`p-2.5 rounded-xl max-w-[85%] text-xs leading-relaxed ${
              msg.sender === 'user' 
                ? 'bg-sky-500/10 border border-sky-500/20 text-sky-300' 
                : 'bg-slate-900/60 border border-slate-800 text-slate-300'
            }`}>
              {msg.text}
            </div>
          </div>
        ))}
      </div>

      <div className="flex gap-2">
        <input 
          type="text" value={input} onChange={(e) => setInput(e.target.value)}
          placeholder="Type your response..." 
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          className="flex-1 bg-slate-900 border border-slate-850 rounded-lg px-3 py-1.5 text-xs text-slate-200 outline-none focus:border-sky-400"
        />
        <button onClick={handleSend} className="bg-sky-400 hover:bg-sky-500 text-slate-950 px-3 py-1.5 rounded-lg text-xs font-bold transition-colors">
          Send
        </button>
      </div>
    </div>
  );
}

// === COMPONENT RESOLVER ===
function renderSlideContent(html) {
  if (!html) return null;

  // 1. Hydrate Chart Markers
  if (html.includes('class="chart-hydration-marker"')) {
    const markerRegex = /<div\s+class="chart-hydration-marker"\s+data-chart-type="([^"]+)"\s+data-dataset="([^"]+)"\s+data-x="([^"]+)"\s+data-y="([^"]+)"\s*>\s*<\/div>/;
    const match = html.match(markerRegex);
    if (match) {
      const parts = html.split(match[0]);
      return (
        <>
          {renderSlideContent(parts[0])}
          <ChartComponent 
            type={match[1]} 
            dataset={match[2]} 
            x={match[3]} 
            y={match[4]} 
          />
          {parts[1] && renderSlideContent(parts[1])}
        </>
      );
    }
  }

  // 2. Hydrate dynamic registry widgets recursively
  const widgets = [
    { tag: /<ROIWidget\s*\/?>/, component: <ROIWidget /> },
    { tag: /<EnrollmentCalculator\s*\/?>/, component: <EnrollmentCalculator /> },
    { tag: /<AskAI\s*\/?>/, component: <AskAI /> },
    { tag: /<SimulationEngine\s*\/?>/, component: <SimulationEngine /> },
    { tag: /<InteractiveTimeline\s*\/?>/, component: <InteractiveTimeline /> },
    { tag: /<AITutor\s*\/?>/, component: <AITutor /> }
  ];

  for (const widget of widgets) {
    if (html.match(widget.tag)) {
      const parts = html.split(widget.tag);
      return (
        <>
          {renderSlideContent(parts[0])}
          {widget.component}
          {parts[1] && renderSlideContent(parts[1])}
        </>
      );
    }
  }

  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}

// === MAIN COMPONENT ===
function App() {
  const { title, author, affiliation, date, tagline, slides } = presentationData;
  
  const [currentSlide, setCurrentSlide] = useState(0);
  const [sidebarWidth, setSidebarWidth] = useState(320);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [theme, setTheme] = useState('dark');
  
  // Timer States
  const [secondsElapsed, setSecondsElapsed] = useState(160); // 2m 40s default
  const [timerRunning, setTimerRunning] = useState(true);
  
  // IST Clock
  const [istTime, setIstTime] = useState('');
  
  // Dragging state
  const isDragging = useRef(false);

  // Clock Update Effect
  useEffect(() => {
    const fmt = new Intl.DateTimeFormat('en-US', {
      timeZone: 'Asia/Kolkata',
      hour: 'numeric',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    });
    const tick = () => setIstTime(fmt.format(new Date()));
    tick();
    const interval = setInterval(tick, 1000);
    return () => clearInterval(interval);
  }, []);

  // Timer Update Effect
  useEffect(() => {
    let interval = null;
    if (timerRunning) {
      interval = setInterval(() => {
        setSecondsElapsed(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [timerRunning]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'ArrowLeft') previousSlide();
      if (e.key === 'ArrowRight') nextSlide();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentSlide]);

  // Expose checkAnswer and switchTab globally for compiled HTML content compatibility
  useEffect(() => {
    window.checkAnswer = function(element, selected, correct) {
      const options = element.parentElement.querySelectorAll('.quiz-option');
      options.forEach(opt => {
        opt.style.pointerEvents = 'none';
        if (opt.textContent.trim().startsWith(correct)) {
          opt.classList.add('correct');
        } else {
          if (opt === element) {
            opt.classList.add('incorrect');
          }
        }
      });
    };

    window.switchTab = function(element, bodyId) {
      const container = element.closest('.tabs-container');
      if (!container) return;
      
      const buttons = container.querySelectorAll('.tab-btn');
      buttons.forEach(btn => {
        btn.classList.remove('active', 'border-sky-400', 'text-sky-400', 'bg-sky-500/10');
        btn.classList.add('border-slate-800', 'text-slate-400');
      });
      
      element.classList.add('active', 'border-sky-400', 'text-sky-400', 'bg-sky-500/10');
      element.classList.remove('border-slate-800', 'text-slate-400');
      
      const bodies = container.querySelectorAll('.tab-body');
      bodies.forEach(body => {
        body.style.display = 'none';
        body.classList.remove('active');
      });
      
      const activeBody = container.querySelector('#' + bodyId);
      if (activeBody) {
        activeBody.style.display = 'block';
        activeBody.classList.add('active');
      }
    };

    window.checkBlank = function(element, correctAnswersStr) {
      const val = element.value.trim().toLowerCase();
      const correctList = correctAnswersStr.split('|').map(a => a.trim().toLowerCase());
      
      // Remove any existing feedback tags next to this element
      const sibling = element.nextElementSibling;
      if (sibling && sibling.classList.contains('blank-feedback')) {
        sibling.remove();
      }
      
      const feedbackSpan = document.createElement('span');
      feedbackSpan.className = 'blank-feedback ml-1.5 font-sans font-bold text-xs inline-flex items-center gap-1';
      
      if (correctList.includes(val)) {
        element.style.backgroundColor = 'rgba(16, 185, 129, 0.15)';
        element.style.borderColor = '#10b981';
        feedbackSpan.style.color = '#10b981';
        feedbackSpan.innerHTML = '&#10004;'; // checkmark tick
      } else {
        element.style.backgroundColor = 'rgba(244, 63, 94, 0.15)';
        element.style.borderColor = '#f43f5e';
        feedbackSpan.style.color = '#f43f5e';
        const rightResponse = correctAnswersStr.split('|')[0];
        feedbackSpan.innerHTML = `&#10008; <span class="text-slate-400 font-normal">(${rightResponse})</span>`; // cross mark + correct answer
      }
      
      element.parentNode.insertBefore(feedbackSpan, element.nextSibling);
    };

    return () => {
      delete window.checkAnswer;
      delete window.switchTab;
      delete window.checkBlank;
    };
  }, []);

  const nextSlide = () => {
    if (currentSlide < slides.length - 1) showSlide(currentSlide + 1);
  };

  const previousSlide = () => {
    if (currentSlide > 0) showSlide(currentSlide - 1);
  };

  const showSlide = (index) => {
    setCurrentSlide(index);
  };

  const formatTimer = () => {
    const mins = Math.floor(secondsElapsed / 60);
    const secs = secondsElapsed % 60;
    return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
  };

  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(err => {
        console.error(`Error attempting to enable fullscreen: ${err.message}`);
      });
    } else {
      document.exitFullscreen();
    }
  };

  // Drag resizing handlers
  const handleMouseDown = (e) => {
    isDragging.current = true;
    document.body.style.cursor = 'col-resize';
    e.preventDefault();
  };

  useEffect(() => {
    const handleMouseMove = (e) => {
      if (!isDragging.current) return;
      const newWidth = e.clientX;
      if (newWidth > 200 && newWidth < 480) {
        setSidebarWidth(newWidth);
      }
    };
    
    const handleMouseUp = () => {
      if (isDragging.current) {
        isDragging.current = false;
        document.body.style.cursor = 'default';
      }
    };

    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, []);

  // Dot Pagination Truncation
  const renderDots = () => {
    const maxDotsVisible = 9;
    let startDot = 0;
    let endDot = slides.length;
    
    if (slides.length > maxDotsVisible) {
      const half = Math.floor(maxDotsVisible / 2);
      startDot = currentSlide - half;
      endDot = currentSlide + half + 1;
      
      if (startDot < 0) {
        startDot = 0;
        endDot = maxDotsVisible;
      } else if (endDot > slides.length) {
        endDot = slides.length;
        startDot = slides.length - maxDotsVisible;
      }
    }
    
    const dots = [];
    for (let i = startDot; i < endDot; i++) {
      dots.push(
        <div 
          key={i}
          onClick={() => showSlide(i)}
          title={slides[i].title}
          className={`transition-all rounded-full cursor-pointer ${
            i === currentSlide 
              ? "w-2.5 h-2.5 bg-sky-400" 
              : "w-1.5 h-1.5 bg-slate-700 hover:bg-slate-500"
          }`}
        />
      );
    }
    return dots;
  };

  // Group slide indexing for Accordion Topics
  const renderSidebarAccordion = () => {
    const activeTopicIdx = slides[currentSlide].topic_idx;
    const accordionGroups = [];
    let currentTopicIndex = -1;
    let currentSubtopics = [];
    
    slides.forEach((slide, index) => {
      if (slide.is_major) {
        if (currentTopicIndex !== -1) {
          accordionGroups.push({
            topicIdx: currentTopicIndex,
            title: slides[currentTopicIndex].title,
            subtopics: currentSubtopics
          });
        }
        currentTopicIndex = index;
        currentSubtopics = [];
      } else {
        currentSubtopics.push({
          index,
          title: slide.title,
          label: slide.label
        });
      }
    });
    
    // Add final group
    if (currentTopicIndex !== -1) {
      accordionGroups.push({
        topicIdx: currentTopicIndex,
        title: slides[currentTopicIndex].title,
        subtopics: currentSubtopics
      });
    }

    return accordionGroups.map((group) => {
      const isTopicExpanded = group.topicIdx === activeTopicIdx;
      return (
        <div key={group.topicIdx} className="mb-2">
          {/* Topic Title Button */}
          <div 
            onClick={() => showSlide(group.topicIdx)}
            style={{
              borderColor: group.topicIdx === currentSlide ? '#E5A823' : 'transparent',
              background: group.topicIdx === currentSlide ? 'rgba(229, 168, 35, 0.15)' : 'transparent',
              color: group.topicIdx === currentSlide ? '#E5A823' : ''
            }}
            className={`slide-item p-2 rounded-lg text-xs font-semibold cursor-pointer transition-all border flex items-center ${
              group.topicIdx === currentSlide ? "text-sky-400" : "text-slate-200 hover:bg-slate-900/60 hover:text-sky-400"
            }`}
          >
            <Bookmark className="h-3.5 w-3.5 text-sky-400 mr-2 shrink-0" />
            <span>{group.title}</span>
          </div>

          {/* Subtopics List */}
          {isTopicExpanded && group.subtopics.length > 0 && (
            <div className="pl-4 mt-1 space-y-1">
              {group.subtopics.map((sub) => (
                <div 
                  key={sub.index}
                  onClick={() => showSlide(sub.index)}
                  style={{
                    borderColor: sub.index === currentSlide ? '#E5A823' : 'transparent',
                    background: sub.index === currentSlide ? 'rgba(229, 168, 35, 0.15)' : 'transparent',
                    color: sub.index === currentSlide ? '#E5A823' : ''
                  }}
                  className={`slide-item p-1.5 rounded-lg text-xs font-medium cursor-pointer transition-all border flex items-center ${
                    sub.index === currentSlide ? "text-sky-400 font-bold" : "text-slate-400 hover:bg-slate-900/60 hover:text-sky-400"
                  }`}
                >
                  <span className="text-slate-600 mr-2 font-mono text-[10px] shrink-0">{sub.label}</span>
                  <span>{sub.title}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      );
    });
  };

  // Render Slide layout structures dynamically
  const activeSlideData = slides[currentSlide];

  // Memoize slide HTML content rendering to prevent re-creating DOM nodes when timer ticks
  const slideContentNode = useMemo(() => {
    if (currentSlide === 0) return null;
    return renderSlideContent(activeSlideData.content);
  }, [currentSlide, activeSlideData.content]);

  return (
    <div className={`flex h-screen w-screen overflow-hidden ${theme === 'light' ? 'theme-light' : ''} bg-slate-950 text-slate-100`}>
      {/* 1. Sidebar Index Panel */}
      <aside 
        id="sidebar-container" 
        style={{ width: sidebarCollapsed ? 0 : `${sidebarWidth}px`, display: sidebarCollapsed ? 'none' : 'flex' }}
        className="relative bg-slate-950/40 border-r border-slate-800 flex-col z-20 shrink-0 transition-all duration-300"
      >
        {/* Sidebar Brand Header */}
        <div className="p-4 border-b border-slate-800/80 bg-slate-950/60 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex items-center justify-center w-9 h-9 rounded-lg bg-sky-500/10 border border-sky-500/20 text-sky-400 text-sm">
              <GraduationCap className="h-5 w-5 text-sky-400" />
            </div>
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-slate-200">{title}</div>
              <div className="text-[10px] text-sky-400 font-medium">{author}</div>
            </div>
          </div>
          <button 
            onClick={() => setSidebarCollapsed(true)} 
            className="text-slate-500 hover:text-white transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
          </button>
        </div>
        
        {/* Accordion List navigation */}
        <nav className="flex-1 overflow-y-auto p-3.5 space-y-1 select-none">
          {renderSidebarAccordion()}
        </nav>
        
        {/* Bottom Talk Timer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/60">
          <div className="text-[10px] uppercase tracking-wider text-slate-500 font-mono mb-2 flex items-center justify-between">
            <span>Talk Timer (Target: 25:00)</span>
            <span className="text-emerald-400 font-semibold flex items-center gap-1 font-mono">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"></span> Active
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono font-bold text-slate-300">{formatTimer()}</span>
            <div className="flex gap-2">
              <button 
                onClick={() => setTimerRunning(!timerRunning)} 
                className="h-6 w-6 rounded bg-slate-900 border border-slate-800 text-slate-400 hover:text-white flex items-center justify-center transition-colors"
              >
                {timerRunning ? <Pause className="h-3.5 w-3.5" /> : <Play className="h-3.5 w-3.5" />}
              </button>
              <button 
                onClick={() => setSecondsElapsed(0)} 
                className="h-6 w-6 rounded bg-slate-900 border border-slate-800 text-slate-400 hover:text-white flex items-center justify-center transition-colors"
              >
                <RotateCcw className="h-3 w-3" />
              </button>
            </div>
          </div>
        </div>
        
        {/* Resize Handle */}
        <div 
          onMouseDown={handleMouseDown} 
          className="absolute top-0 right-0 w-1 h-full cursor-col-resize hover:bg-sky-400/40 active:bg-sky-400 transition-colors z-30"
        />
      </aside>

      {/* Floating expand button */}
      {sidebarCollapsed && (
        <button 
          onClick={() => setSidebarCollapsed(false)}
          className="fixed bottom-6 left-6 h-10 w-10 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-700 shadow-2xl flex items-center justify-center z-50 transition-all duration-300"
        >
          <ChevronRight className="h-5 w-5" />
        </button>
      )}

      {/* 2. Main Slides Display Workspace */}
      <div className="flex flex-col h-full flex-1 overflow-hidden">
        {/* Top Header Navigation */}
        <header className="h-16 border-b border-slate-800 bg-slate-950/80 backdrop-blur px-6 flex items-center justify-between z-30 shrink-0 select-none">
          <div className="flex items-center gap-3">
            <div className="text-xs font-bold uppercase tracking-wider bg-sky-500/10 border border-sky-500/20 px-2.5 py-1 rounded text-sky-400">
              {title}
            </div>
            <span className="text-slate-500">|</span>
            <span className="text-xs font-medium text-slate-300">{activeSlideData.title}</span>
          </div>
          
          <div className="flex items-center gap-4">
            <span className="text-xs text-slate-400 hidden lg:inline">Presenter: <strong className="text-slate-200">{author}</strong></span>
            
            {/* Live IST Clock */}
            <div className="flex items-center gap-2 bg-slate-900 border border-slate-800 rounded-full px-3.5 py-1 text-slate-300 text-xs font-mono">
              <Clock className="h-3.5 w-3.5 text-sky-400" />
              <span>{istTime}</span>
              <span className="text-[9px] text-slate-500 tracking-wider">IST &bull; INDIA</span>
            </div>
            
            <button 
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              className="h-9 w-9 rounded-lg bg-slate-900 border border-slate-800 text-slate-400 hover:text-white flex items-center justify-center transition-colors animate-fade-up"
            >
              {theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </button>
            <button 
              onClick={toggleFullscreen}
              className="h-9 w-9 rounded-lg bg-slate-900 border border-slate-800 text-slate-400 hover:text-white flex items-center justify-center transition-colors"
            >
              <Maximize2 className="h-4 w-4" />
            </button>
          </div>
        </header>

        {/* Viewport content area */}
        <main className="flex-1 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 relative overflow-y-auto p-4 md:p-8 flex items-center justify-center max-h-[calc(100vh-9rem)]">
          <div className="w-full max-w-4xl max-h-[calc(100vh-11rem)] overflow-y-auto rounded-2xl relative">
            <div className="slide slide-container slide-active">
              <div className="bg-slate-900/40 border border-slate-800/50 backdrop-blur rounded-2xl p-6 md:p-8 shadow-2xl animate-fade-up">
                
                {/* Dynamically Render Layout templates */}
                {currentSlide === 0 ? (
                  <div className="text-center py-6">
                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-sky-500/10 border border-sky-500/20 text-sky-400 text-[10px] font-bold uppercase tracking-widest mb-6 font-mono">
                      <BookOpen className="h-3 w-3" /> Next Frontier of AI
                    </span>
                    <h1 className="text-5xl font-bold font-serif mb-4 text-slate-100 tracking-tight">{title}</h1>
                    <p className="text-lg italic text-sky-400 mb-8 font-serif">{tagline}</p>
                    <p className="text-sm text-slate-400 max-w-xl mx-auto mb-12 leading-relaxed">
                      An interactive, full-fledged React-rendered template demonstrating multi-column grids, live calculations, dynamic graphing, and adaptive H5P checks.
                    </p>
                    
                    {/* 3-Column Metadata Card Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-3xl mx-auto pt-8 border-t border-slate-800/60 text-left mt-12">
                      <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/40">
                        <span className="text-[10px] uppercase tracking-wider text-slate-500 font-mono font-bold block mb-1">Presented By</span>
                        <div className="flex items-center gap-2 text-slate-200 text-sm font-semibold">
                          <User className="h-4 w-4 text-sky-400" /> {author}
                        </div>
                      </div>
                      <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/40">
                        <span className="text-[10px] uppercase tracking-wider text-slate-500 font-mono font-bold block mb-1">Date</span>
                        <div className="flex items-center gap-2 text-slate-200 text-sm font-semibold">
                          <Calendar className="h-4 w-4 text-sky-400" /> {date}
                        </div>
                      </div>
                      <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/40">
                        <span className="text-[10px] uppercase tracking-wider text-slate-500 font-mono font-bold block mb-1">Hosted By</span>
                        <div className="flex items-center gap-2 text-slate-200 text-sm font-semibold">
                          <Award className="h-4 w-4 text-sky-400" /> {affiliation}
                        </div>
                      </div>
                    </div>
                  </div>
                ) : (
                  slideContentNode
                )}

              </div>
            </div>
          </div>
        </main>

        {/* Footer controls */}
        <footer className="h-20 border-t border-slate-800 bg-slate-950/80 backdrop-blur px-6 flex flex-col items-center justify-center z-30 shrink-0 relative select-none">
          <div className="flex items-center justify-between w-full">
            <button 
              id="prev-btn" 
              onClick={previousSlide}
              disabled={currentSlide === 0}
              className="nav-button border border-slate-800 bg-slate-900/50 text-slate-300 font-medium hover:border-slate-700 hover:text-white disabled:opacity-40 transition-all py-1.5 px-4 rounded-lg flex items-center gap-2 text-xs"
            >
              <ChevronLeft className="h-4 w-4" /> Previous
            </button>
            
            {/* Center dot indicators window pagination */}
            <div className="flex flex-col items-center gap-1.5">
              <div className="flex items-center gap-2" id="jump-dots">
                {renderDots()}
              </div>
              <div id="slide-progress" className="text-[10px] font-mono text-slate-500">
                Presenter: {author} &bull; Slide {currentSlide + 1} of {slides.length}
              </div>
            </div>
            
            <button 
              id="next-btn" 
              onClick={nextSlide}
              disabled={currentSlide === slides.length - 1}
              className="nav-button bg-sky-400 text-slate-950 font-bold hover:bg-sky-500 disabled:opacity-40 transition-all py-1.5 px-4 rounded-lg flex items-center gap-2 text-xs"
            >
              Next <ChevronRight className="h-4 w-4 text-slate-950" />
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;
